<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="views/css/style.css?v=<?php echo time(); ?>">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <title>Sala de chat</title>
</head>
<body style="background-color: #eee;">
<nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="index.php">Inicio</a>
                    </li>
                    <?php
                if(!$_SESSION['user']->getName()){
                    echo '<li class="nav-item">
                    <a class="nav-link" href="index.php?login">Login</a>
                    </li>';
                }else{
                    echo '<li class="nav-item">';
                    echo '<a class="nav-link" href="index.php?login&logout">Salir</a>
                    </li>';
                    if($_SESSION['user']->getRol()==1){
                        echo '<li class="nav-item">
                        <a class="nav-link" href="index.php?admin">Panel de administración</a>
                        </li>';
                    }
                ?>
                </ul>
            </div>
            <?php 
            echo '<li class="navbar-brand">'.$_SESSION['user']->getName().'</li> ';
                  }
            ?>
        </div>
    </nav>
<section>
  <div class="container py-auto">

    <div class="row">
      
      <div class="col-md-6 col-lg-7 col-xl-8">
      <?php
      
    if(!$_SESSION['user']->getName()){
        echo '<h3 class="mb-5">Inicia sesión para poder participar en el chat</h3>';
    }else{
      echo '<div class="main overflow-auto">';
      echo'<div class="container">';
        foreach($messages as $message) {
          echo '<div class="chat-log">';
          if($message->getId_user()==$_SESSION['user']->getId()){
            echo '<div class="chat-log__item chat-log__item--own">
                <h3 class="chat-log__author">'.UserRepository::getUserByID($message->getId_user())->getName().' <small>'.$message->getMessage_date().' - '.$message->getMessage_hora().'</small></h3>
                <div class="chat-log__message">'.$message->getMessage().'</div>
                </div>';
          }else{
              echo'<div class="chat-log__item">
              <h3 class="chat-log__author">'.UserRepository::getUserByID($message->getId_user())->getName().' <small>'.$message->getMessage_date().' - '.$message->getMessage_hora().'</small></h3>
                <div class="chat-log__message">'.$message->getMessage().'</div>
           </div>';
        }
        echo'</div>
          '; 
        }   
        echo'</div>
        </div>';
        
    }   

  ?>
      
  </div>
  <div class="chat-form">
          <div class="container">
             <form action="index.php?enviar" class="form-horizontal" method="POST">
              <div class="row">
                <div class="col-sm-10 col-xs-8">
                  <input type="text" class="form-control" name="text" placeholder="Envía un mensaje..." required/>
                </div>
                <div class="col-sm-2 col-xs-4">
                  <button type="submit" name="send" class="btn btn-success btn-block">Enviar mensaje</button>
                </div>
              </div>
            </form>
          </div>
        </div>
        <?php 
        if($_SESSION['user']->getName()){
          echo '<div class="col overflow-auto">
          <ul class="list-group mb-5">
          <h3>Lista de usuarios conectados:</h3>';
            foreach($users as $user){
              if(in_array($user->getName(),$enlinea)){
                echo '<a href="index.php?pm='.$user->getId().'" class="list-group-item list-group-item-success w-50 mb-1" >'.$user->getName().'</a>';
              }
            }
          echo '</ul>
          <form action="index.php?añadir"  method="POST">
            <button class= "btn btn-info btn-lg">Crear sala</button>
            <input type="text" placeholder="nombre de la sala" name="chatname"></input>
          </form>
          <ul class="list-group">
            <h3>Lista de salas de chat:</h3>';
            foreach($chats as $chat){
              echo '<a href="index.php?chat='.$chat->getId().'" class="list-group-item list-group-item-action">'.$chat->getName().'</a>';
            };
          echo '</ul>
          </div>';
        }
        ?>
      
      </div>
  </div>
  </section>        
</body>
</html>